# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-02 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='content_type',
            field=models.CharField(default='text', max_length=200),
        ),
    ]
