# Generated by Django 2.0.3 on 2018-05-19 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0003_auto_20180107_1508'),
    ]

    operations = [
        migrations.RenameField(
            model_name='object',
            old_name='file',
            new_name='file_obj',
        ),
    ]
