# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-09 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='title')),
                ('subtitle', models.CharField(blank=True, default=b'', max_length=256, verbose_name='subtitle')),
                ('content', models.TextField(blank=True, default=b'', verbose_name='content')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='date')),
                ('last_modified', models.DateTimeField(auto_now_add=True, null=True, verbose_name='modified')),
                ('code', models.IntegerField(default=200, verbose_name='code')),
            ],
            options={
                'ordering': ['title'],
                'verbose_name': 'wiki',
            },
        ),
        migrations.CreateModel(
            name='ModifyHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField(default=0, verbose_name='state')),
                ('code', models.CharField(default=b'', max_length=64, verbose_name='code')),
                ('title', models.CharField(max_length=256, verbose_name='title')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='timestamp')),
                ('editor', models.CharField(max_length=256, verbose_name='editor')),
                ('diff', models.TextField(blank=True, default=b'', verbose_name='diff')),
            ],
            options={
                'ordering': ['timestamp'],
                'verbose_name': 'wiki_history',
            },
        ),
    ]
