# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-05-01 13:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion

from wiki.models import *


def migrate_data(apps, schema_editor):
    for article in Article.objects.all():
        if article.is_public:
            permission = DocumentPermission.PUBLIC
        else:
            permission = DocumentPermission.LOGIN_USER

        document = Document(title=article.title, content=article.content, permission=permission)
        document.save()

        revision = DocumentRevision(document=document, editor="MIGRATED")
        revision.save()


class Migration(migrations.Migration):
    dependencies = [
        ('wiki', '0002_article_is_public'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(blank=True, default=b'')),
                ('permission', models.IntegerField(default=1)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentRevision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_created=True)),
                ('revision', models.IntegerField(default=1)),
                ('editor', models.CharField(max_length=256, verbose_name='editor')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wiki.Document')),
            ],
        ),
        migrations.RunPython(migrate_data),
    ]
