# Generated by Django 2.0.1 on 2018-01-06 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0003_document_documentrevision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(blank=True, default='', verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='article',
            name='subtitle',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='subtitle'),
        ),
        migrations.AlterField(
            model_name='document',
            name='content',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='document',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='permission',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='documentrevision',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='modifyhistory',
            name='code',
            field=models.CharField(default='', max_length=64, verbose_name='code'),
        ),
        migrations.AlterField(
            model_name='modifyhistory',
            name='diff',
            field=models.TextField(blank=True, default='', verbose_name='diff'),
        ),
    ]
