# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 07:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusDashboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_id', models.CharField(max_length=10)),
                ('bus_number', models.CharField(max_length=10)),
                ('station_id', models.CharField(max_length=10)),
                ('station_name', models.CharField(max_length=40)),
            ],
            options={
                'ordering': ['bus_id'],
                'verbose_name': 'busdashboard',
            },
        ),
    ]
