# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-22 07:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'category',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='date')),
                ('preview', models.CharField(blank=True, max_length=256, null=True, verbose_name='preview')),
                ('tags', models.TextField(default=b'', max_length=256)),
                ('title', models.CharField(max_length=256, verbose_name='title')),
                ('description', models.TextField(blank=True, default=b'', verbose_name='description')),
                ('content', models.TextField(blank=True, default=b'', verbose_name='content')),
                ('public_post', models.BooleanField(default=False)),
                ('posttype', models.CharField(max_length=20, verbose_name='posttype')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Category', verbose_name='category')),
            ],
            options={
                'ordering': ['created'],
                'verbose_name': 'post',
            },
        ),
        migrations.CreateModel(
            name='PostType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('icon', models.CharField(max_length=50)),
                ('default', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PostTypeRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.IntegerField()),
                ('type_id', models.IntegerField()),
            ],
        ),
    ]
