# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-04 06:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='url',
            field=models.CharField(default=b'', max_length=32),
        ),
    ]
